### PR TITLE
Pretrained models added

### PR DESCRIPTION
**Pull request by ZFTurbo**
May be it's good idea to move all pretrained H5-files, inference and training code directly to this Repo. Just need to find the right place where to put files with code.

### CODE REVIEW

**Comment by hgaiser** [comment]
Ah cool, very nice contribution! I'm thinking maybe it is better if we host the model files in the releases page of keras-maskrcnn, what do you think?

**Comment by ZFTurbo** [comment]
@hgaiser, sure. Fill free to copy model files in this repository.

**Comment by vcarpani** [comment]
Thanks for the contribution ;)

**Comment by hgaiser** [comment]
I've reworded the entry in the README a bit, thank you for the contribution!

**Pull request merged**
